name: IntegrationTest

on:
  workflow_dispatch:
  pull_request:
    branches:
      - int

permissions: read-all

jobs:
  integration-test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
      - name: Set up Go
        uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4
        with:
          go-version: 1.19
      - run: sudo go test -v
      - run: go build -ldflags="-s -w" -o ./agent
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@ea7b857d8a33dc2fb4ef5a724500044281b49a5e
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - run: aws s3 cp ./agent s3://step-security-agent/refs/heads/int/agent --acl public-read
      - name: Integration test
        uses: docker://ghcr.io/step-security/integration-test/int:latest@sha256:947868b3c9f456695d89a06ef9c1a9194a579f0b2bd5a724a4b864b9a0d6787d
        env:
          PAT: ${{ secrets.PAT }}
